---
# Defaults for vm_network_docker role
vm_network_docker_new_disk: /dev/vdb
vm_network_docker_new_mount: /mnt/docker-new
vm_network_docker_data_dir: /var/lib/docker
vm_network_docker_fs_type: ext4
vm_network_docker_backup_dir: /var/lib/docker.old
vm_network_docker_tmp_mount: /mnt/docker-new
vm_network_docker_already_migrated: false

# UniFi configuration
vm_network_docker_unifi_system_ip: "{{ ansible_default_ipv4.address }}"
vm_network_docker_unifi_dir: /opt/unifi
vm_network_docker_unifi_compose_file: "{{ vm_network_docker_unifi_dir }}/docker-compose.yml"
vm_network_docker_unifi_data_dir: /opt/unifi/data
vm_network_docker_unifi_wait_timeout: 60

# Backup configuration
vm_network_docker_backup_paths:
  - /opt/netbox/configuration
  - /opt/netbox/env
  - /opt/netbox/docker-compose.yml
  - /opt/unifi/docker-compose.yml

# Netbox configuration (from existing env/netbox.env)
vm_network_docker_netbox_db_password: "J5brHrAXFLQSif0K"
vm_network_docker_netbox_secret_key: "r(m)9nLGnz$(_q3N4z1k(EFsMCjjjzx08x9VhNVcfd%6RF#r!6DE@+V5Zk2X"
vm_network_docker_redis_password: "H733Kdjndks81"
vm_network_docker_redis_cache_password: "t4Ph722qJ5QHeQ1qfu36"
